### ISSUE TITLE
Отсутствующие скиллы для 33 и 34 оружия

### ISSUE THREAD

**Issue by NexiusTailer** [Open-GTO/weaponskill#1]
В [массиве](https://github.com/Open-GTO/weaponskill/blob/master/weaponskill.inc#L38-L50) отсутствуют скиллы для винтовки и снайперки. Они под номером 10 (WEAPONSKILL_SNIPERRIFLE).

**Comment by ziggi** [comment]
Он не работает же, смысл в нём?
https://github.com/Open-GTO/weaponskill/commit/1da4fa7259c47663653482db58cdcd48166fb1d0

**Comment by NexiusTailer** [comment]
А, забыл об этом. Хотя для полноты картины это можно было бы иметь хотя бы в массиве.
